package app.smallthingz.timetravel

object TimeTravelConfig {
    const val PACKAGE_NAME = "app.smallthingz.timetravel"

    const val AUDIO_MEMORY_ENABLED_KEY = "audio_memory_enabled"
    const val AUDIO_MEMORY_SIZE_KEY = "audio_memory_size"
    const val BUFFER_DISK_CACHE_ENABLED_KEY = "buffer_disk_cache_enabled"
    const val AGGRESSIVE_RESTART_ENABLED_KEY = "aggressive_restart_enabled"
    const val WAKE_LOCK_ENABLED_KEY = "wake_lock_enabled"
    const val RETENTION_MODE_KEY = "retention_mode"
    const val RETENTION_SECONDS_KEY = "retention_seconds"
    const val EXPORT_DIRECTORY_URI_KEY = "export_directory_uri"
    const val OUTPUT_FORMAT_KEY = "output_format"
    const val OUTPUT_CODEC_KEY = "output_codec"
    const val OUTPUT_BITRATE_KBPS_KEY = "output_bitrate_kbps"
    const val AUDIO_SOURCE_KEY = "audio_source"
    const val CHANNEL_MODE_KEY = "channel_mode"
    const val INPUT_ROUTE_KEY = "input_route"
    const val SAMPLE_RATE_KEY = "sample_rate"
    const val THEME_MODE_KEY = "theme_mode"
    const val HISTORY_CHUNK_SECONDS_KEY = "history_chunk_seconds"
    const val AUTO_MERGE_MODE_KEY = "auto_merge_mode"
    const val AUTO_MERGE_DIVISOR_KEY = "auto_merge_divisor"
    const val AUTO_MERGE_CUSTOM_SECONDS_KEY = "auto_merge_custom_seconds"
    const val AUTO_MERGE_CUSTOM_SIZE_MIB_KEY = "auto_merge_custom_size_mib"
    const val DEBUG_CHUNKS_TAB_ENABLED_KEY = "debug_chunks_tab_enabled"
    const val CUSTOM_EXPORT_MODE_KEY = "custom_export_mode"
    const val CUSTOM_EXPORT_UNIT_KEY = "custom_export_unit"
    const val CUSTOM_EXPORT_PAST_SECONDS_KEY = "custom_export_past_seconds"
    const val CUSTOM_EXPORT_PAST_SIZE_MIB_KEY = "custom_export_past_size_mib"

    const val RETENTION_MODE_SIZE = "size"
    const val RETENTION_MODE_TIME = "time"

    const val OUTPUT_FORMAT_WAV = "wav"
    const val OUTPUT_FORMAT_M4A = "m4a"
    const val OUTPUT_FORMAT_3GP = "3gp"
    const val OUTPUT_FORMAT_OGG = "ogg"
    const val OUTPUT_FORMAT_WEBM = "webm"
    const val OUTPUT_FORMAT_AAC_ADTS = "aac_adts"
    const val OUTPUT_FORMAT_AMR_NB = "amr_nb_file"
    const val OUTPUT_FORMAT_AMR_WB = "amr_wb_file"
    const val OUTPUT_FORMAT_MPEG_2_TS = "mpeg_2_ts"

    const val OUTPUT_CODEC_WAV = "wav"
    const val OUTPUT_CODEC_PCM_16 = "pcm_16"
    const val OUTPUT_CODEC_AAC = "aac"
    const val OUTPUT_CODEC_AAC_LC = "aac_lc"
    const val OUTPUT_CODEC_AAC_ELD = "aac_eld"
    const val OUTPUT_CODEC_HE_AAC = "he_aac"
    const val OUTPUT_CODEC_HE_AAC_V2 = "he_aac_v2"
    const val OUTPUT_CODEC_XHE_AAC = "xhe_aac"
    const val OUTPUT_CODEC_AMR_WB = "amr_wb"
    const val OUTPUT_CODEC_AMR_NB = "amr_nb"
    const val OUTPUT_CODEC_OPUS = "opus"
    const val OUTPUT_CODEC_VORBIS = "vorbis"
    const val OUTPUT_CODEC_FLAC = "flac"

    const val CHANNEL_MODE_MONO = "mono"
    const val CHANNEL_MODE_STEREO = "stereo"
    const val INPUT_ROUTE_AUTO = "auto"
    const val INPUT_ROUTE_BUILTIN_MIC = "builtin_mic"
    const val THEME_MODE_SYSTEM = "system"
    const val THEME_MODE_LIGHT = "light"
    const val THEME_MODE_DARK = "dark"
    const val AUTO_MERGE_MODE_OFF = "off"
    const val AUTO_MERGE_MODE_RATIO = "ratio"
    const val AUTO_MERGE_MODE_CUSTOM = "custom"
    const val AUTO_MERGE_MODE_CUSTOM_TIME = "custom_time"
    const val AUTO_MERGE_MODE_CUSTOM_SIZE = "custom_size"
    const val CUSTOM_EXPORT_MODE_RANGE = "range"
    const val CUSTOM_EXPORT_MODE_PAST = "past"
    const val CUSTOM_EXPORT_UNIT_TIME = "time"
    const val CUSTOM_EXPORT_UNIT_SIZE = "size"

    const val APP_STORAGE_FOLDER_NAME = "Timetravel"
    const val BUFFER_CACHE_FOLDER_NAME = "buffer-cache"
}
